#!/bin/bash -e
#
# Simple script to build risu for all architectures
#
# Copyright (c) 2017 Linaro Limited
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Peter Maydell (Linaro) - initial implementation

# So we notice risugen failing even though it's in a pipeline
set -o pipefail

# Debian stretch and Ubuntu Xenial have cross compiler packages for
# all of these:
# gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-m68k-linux-gnu
# gcc-powerpc64le-linux-gnu gcc-powerpc64-linux-gnu

program_exists() {
    command -v "$1" >/dev/null 2>&1
}

# powerpc64-linux-gnu doesn't work at the moment, so not yet listed.
for triplet in aarch64-linux-gnu arm-linux-gnueabihf m68k-linux-gnu \
    powerpc64le-linux-gnu ; do

    if ! program_exists "${triplet}-gcc"; then
        echo "Skipping ${triplet}: no compiler found"
        continue
    fi

    # Do a complete rebuild from scratch, because it's cheap enough.
    rm -rf build/${triplet}
    mkdir -p build/${triplet}

    (cd build/${triplet} && CROSS_PREFIX="${triplet}-"  ../../configure)
    make -C build/${triplet}

done

# Now run risugen for all architectures
mkdir -p build/risuout

for f in *.risu; do
    echo "Running risugen on $f..."
    # The grep is a quick hack to avoid flooding the terminal with an
    # enormous list of patterns. Ideally we should make risugen
    # have a --quiet option or similar.
    ./risugen --numinsns 10000 $f build/risuout/$f.out | grep -v '^Generating code using patterns'
done
